name: First-Github-Action-Workflow
on:
  push:
    branches: [ main ]

jobs:
  demo-github-action:
    runs-on: ubuntu-latest

    steps:
      - name: Print-Greeting-Message
        run: echo "Hello, Welcome to GitHub Actions Workflow"
